# Auto-generated config. Do not edit manually.
config = {'batch_size': 32,
 'data_path': 'deepmimo_data.pkl',
 'device': 'cuda',
 'exp_decay': 0.5,
 'learning_rate': 0.0015,
 'model_type': 'transformer',
 'num_rx': 4,
 'num_samples': 10000,
 'num_tx': 4,
 'pilot_length': 8,
 'quant_bits': 4,
 'snr_db': 'random',
 'train_epoch': 15,
 'use_deepmimo': True}
